export const branches = [
  "Vernon Hills, IL (Corporate Headquarters)",
  "Bensenville, IL",
  "Bethlehem, PA",
  "Brooklyn Heights, OH (Cleveland)",
  "Columbus, OH",
  "Eagan, MN (Holdahl)",
  "Edison, NJ",
  "Harrisburg, PA",
  "Indianapolis, IN",
  "Kansas City, MO",
  "Leetsdale, PA",
  "Londonderry, NH (Akins Machinery)",
  "Middletown, OH (Cincinnati/Dayton)",
  "Oak Park, MI (Detroit)",
  "Omaha, NE (Holdahl)",
  "Philadelphia / Pennsauken, NJ",
  "Pleasant Hill, Iowa (Holdahl)",
  "Plymouth, MN (Holdahl)",
  "Rumford, RI",
  "Sanford, NC (J&G Machinery)",
  "Sioux Falls, SD (Holdahl)",
  "Syracuse, NY",
  "Versailles, KY (Lexington)",
  "West Haven, CT",
  "Williamsport, PA (Hermance)"
];
